import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createPullRequest } from './createPr.js';
import { logger } from '../logging/logger.js';

const execFileAsync = promisify(execFile);

async function git(cwd: string, args: string[]): Promise<string> {
  const { stdout } = await execFileAsync('git', args, {
    cwd,
    timeout: 30_000,
    maxBuffer: 5 * 1024 * 1024,
  });
  return stdout.trim();
}

async function hasUncommittedChanges(cwd: string): Promise<boolean> {
  const status = await git(cwd, ['status', '--porcelain']);
  return status.length > 0;
}

async function getDefaultBranch(cwd: string): Promise<string> {
  try {
    const ref = await git(cwd, ['symbolic-ref', 'refs/remotes/origin/HEAD', '--short']);
    return ref.replace('origin/', '');
  } catch {
    return 'main';
  }
}

/**
 * After a pipeline run, detect uncommitted changes in the workspace,
 * create a branch, commit, push, and open a PR.
 *
 * Returns the PR URL if successful, or undefined if no changes or on failure.
 */
export async function createPrFromWorkspace(params: {
  repoPath: string;
  threadTs: string;
  summary: string;
  onLog?: (msg: string) => void;
}): Promise<string | undefined> {
  const { repoPath, threadTs, summary, onLog } = params;

  try {
    const hasChanges = await hasUncommittedChanges(repoPath);
    if (!hasChanges) {
      onLog?.('No uncommitted changes in workspace, skipping PR creation.');
      return undefined;
    }

    const safeBranchTs = threadTs.replace(/[^a-zA-Z0-9.-]/g, '-');
    const branchName = `watchtower/fix-${safeBranchTs}`;
    const baseBranch = await getDefaultBranch(repoPath);

    // Check if we're in a detached HEAD (worktree) and create branch from it
    const currentBranch = await git(repoPath, ['rev-parse', '--abbrev-ref', 'HEAD']).catch(() => 'HEAD');

    if (currentBranch === 'HEAD') {
      // Detached HEAD — create and checkout a new branch
      await git(repoPath, ['checkout', '-b', branchName]);
    } else {
      // Already on a branch — create a new one from current
      await git(repoPath, ['checkout', '-b', branchName]);
    }

    onLog?.(`Created branch: ${branchName}`);

    // Stage all changes
    await git(repoPath, ['add', '-A']);

    // Commit
    const commitTitle = summary.length > 72
      ? `${summary.slice(0, 69)}...`
      : summary;
    await git(repoPath, ['commit', '-m', commitTitle]);
    onLog?.('Committed changes.');

    // Push
    await git(repoPath, ['push', '-u', 'origin', branchName]);
    onLog?.(`Pushed to origin/${branchName}.`);

    // Create PR
    const prBody = [
      '## Summary',
      summary,
      '',
      `Thread: ${threadTs}`,
      '',
      'Generated by Watchtower multi-agent pipeline.',
    ].join('\n');

    const { prUrl } = await createPullRequest({
      repoPath,
      title: commitTitle,
      body: prBody,
      branch: branchName,
      baseBranch,
    });

    onLog?.(`PR created: ${prUrl}`);
    return prUrl;
  } catch (error) {
    logger.warn({ repoPath, threadTs, error: String(error) }, 'failed to create PR from workspace changes');
    onLog?.(`PR creation failed: ${String(error)}`);
    return undefined;
  }
}
